// <auto-generated />
using System;
using BOAMP_SITE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BOAMP_SITE.Migrations
{
    [DbContext(typeof(FavorisDbContext))]
    [Migration("20240309170631_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("BOAMP_SITE.Data.Favori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAjout")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateFinDiffusion")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdAvis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Objet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Favoris");
                });
#pragma warning restore 612, 618
        }
    }
}
